### PR TITLE
Add some tests for the issue transferring options

### LINKED ISSUE #38: Add testing for issue ticket transferring options
Add testing for issue ticket transferring options

### PR DESCRIPTION
**Pull request by gridhead**
I have added those environment variables to the repository's collection of secrets.

That is how it is working but these might need to be refreshed down the road when these API secrets expire.

Fixes #38

### CODE REVIEW

**Comment by gridhead** [comment]
I am at a loss here.

I have assigned these to the repository secrets but for some reason, I cannot assign them to the user-wide environment variables in the container where this is running.

image

The last attempt was made here https://github.com/gridhead/protop2g/pull/32/commits/b8f8cc7471288254eb460869b2e4a5aaec7def6b.

I might add some more commits to play around debugging how the variables work in GitHub Actions.

**Comment by gridhead** [comment]
The lines 6 and 7 are empty in the log https://github.com/gridhead/protop2g/actions/runs/6506971308/job/17673535066?pr=32#step:7:1.

Now, this can point to one of the following possibilities.

- This can be a security feature for preventing someone from inadvertently exposing their environment secrets
- The assignments of environment variables in the previous stage did not quite work the way they should have 
- The assignments of environment variables in the previous stage are restricted to references made there only

The next thing I will do is try having all the processes of assigning environment variables and using them in either multiple commands across one stage or just one command in one stage to check if the context is not lost while moving through stages.

**Comment by gridhead** [comment]
Apparently, environment secrets work just fine being assigned to environment variables as it is mentioned in their documentation (which you can find here https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-of-jobsjob_idstepsenv) so there was no need to export environment variables like that for those. Thanks @abompard for digging it up and helping me out with this.

**Review by samyak-jn — APPROVED** [review]
Hello @gridhead 

Thanks for explaining the confusing bit to me, I couldn't find anything strange in this, you have +1 for this! Thanks :rocket:

**Pull request merged**
